description: >- # used by seo meta and the atom feed
# Fill in the protocol & hostname for your site.
# e.g. 'https://username.github.io', note that it does not end with a '/'.
url: "https://Programista.github.io"

github:
  username: Programista # change to your github username
twitter:
  username: twitter_username # change to your twitter username
social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: your_full_name
  email: example@domain.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/username # change to your twitter homepage
    - https://github.com/Programista # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code

# Theme Settings
theme: jekyll-theme-minimal # change to your desired theme

# Optional settings for remote theme
# remote_theme: owner/repo
# example: remote_theme: pages-themes/minimal
